// Code generated by "stringer -type=Rank"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Joker-0]
	_ = x[Ace-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[Four-4]
	_ = x[Five-5]
	_ = x[Six-6]
	_ = x[Seven-7]
	_ = x[Eight-8]
	_ = x[Nine-9]
	_ = x[Ten-10]
	_ = x[Jake-11]
	_ = x[Queen-12]
	_ = x[King-13]
}

const _Rank_name = "JokerAceTwoThreeFourFiveSixSevenEightNineTenJakeQueenKing"

var _Rank_index = [...]uint8{0, 5, 8, 11, 16, 20, 24, 27, 32, 37, 41, 44, 48, 53, 57}

func (i Rank) String() string {
	if i < 0 || i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
